image: python:3.12-slim

workflow: 
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

default:
  before_script:
    - python --version ; pip --version
    - pip install uv
    - uv venv .venv
    - source .venv/bin/activate
    - uv pip install -r requirements.txt
    - uv pip install -r requirements-dev.txt
    - uv pip install --editable .

stages:
  - code analysis and testing

pylint:
  stage: code analysis and testing
  script:
    - pylint qlearning
    - pylint examples

pytest:
  stage: code analysis and testing
  script:
    - pytest -v tests
