[project]
name = "qlearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "qiskit>=1.4.0",
    "qiskit-machine-learning>=0.8.2",
    "torch>=2.5.0",
    "tqdm",
    "scikit-learn",
    "pandas",
    "requests",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["qlearning"]

[project.optional-dependencies]
test = ["pytest", "pylint", "pre-commit"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
